easy_admin:
    site_name: 'BrillenHof'
    entities:
        Tags:
            class: App\Entity\Tags
            form:
                fields:
                    - guid
        Urls:
            class: App\Entity\Urls
            list:
                fields: ['id', 'url', 'created']
        ProductUrl:
            class: App\Entity\ProductUrl
            label: 'Адреса продуктов'
            list:
                title: 'Адреса продуктов'
                fields: ['id', 'url', 'created']
            form:
                fields:
                    - url
        CatalogUrl:
            class: App\Entity\CatalogUrl
            label: 'Адреса каталогов'
            list:
                title: 'Адреса продуктов'
                fields: ['id', 'url', 'created']
            form:
                fields:
                  - url
        Users:
            class: App\Entity\Users
            label: 'Пользователи'
            list:
                title: 'Пользователи'
                fields: ['id', 'email', 'roles']
        Menu:
            class: App\Entity\Menu
            label: 'Меню'
            controller: App\Controller\Admin\MenuController
            list:
                title: 'Меню'
                fields: ['id', 'name', 'title']
            form:
                fields:
                  - name
                  - title
        MenuItem:
            label: 'Пункты меню'
            class: App\Entity\MenuItem
            list:
                title: 'Пункты меню'
                fields: ['id', 'title']
        Catalog:
            class: App\Entity\Catalog
            label: 'Каталоги'
            controller: App\Controller\Admin\CatalogController
            list:
                title: 'Каталоги'
                fields: ['id', 'name', 'visible']
            form:
              fields:
                  - { type: 'tab' , label: 'General' }
                  - visible
                  - name
                  - { type: 'tab', label: 'Virtual Urls' }
                  - { property: 'catalogUrls', type_options: { block_name: 'catalog_urls' }}
                  - { type: 'tab', label: 'Tags' }
                  - { property: 'productTagItems', type_options: { block_name: 'catalogs_tags' }}
        Items:
            class: App\Entity\ProductItem
            label: 'Товары'
            controller: App\Controller\Admin\ItemsController
            list:
                title: 'Товары'
                fields:
                    - id
                    - name
            form:
                fields:
                    - { type: 'tab' , label: 'General' }
                    - name
                    - price
                    - { property: 'product_id', type_options: { block_name: 'entity_id'} }
                    - { type: 'tab', label: 'Images' }
                    - { property: 'productItemImages', type_options: { block_name: 'item_images' }}
        Product:
            class: App\Entity\Product
            label: 'Продукты'
            controller: App\Controller\Admin\ProductController
            list:
                title: 'Продукты'
                fields: ['id', 'name', 'visible']
            form:
                fields:
                    - { type: 'tab' , label: 'General' }
                    - visible
                    - name
                    - { type: 'tab', label: 'Categories' }
                    - { property: 'catalog', type_options: { block_name: 'products_catalogs' }}
                    - { type: 'tab', label: 'Product Items'}
                    - { property: 'productItems', type_options: { block_name: 'products_items' }}
                    - { type: 'tab', label: 'Virtual Urls' }
                    - { property: 'productUrls', type: 'form', type_options: {block_name: 'products_urls'}}
                    - { type: 'tab', label: 'Tags' }
                    - { property: 'producttagitem', type_options: { block_name: 'products_tags_items' }}
        Order:
            class: App\Entity\Orders
            controller: App\Controller\Admin\OrderController
            list:
                fields: ['id', 'name', 'visible']
        Delivery:
              class: App\Entity\Delivery
              list:
                  fields: ['id', 'name', 'visible']
        PaymentMethod:
            class: App\Entity\PaymentMethod
            list:
                fields: ['id', 'name']
        ImportProduct:
            class: App\Entity\ImportProduct
            controller: App\Controller\Admin\ImportProductController
        ProductTag:
            class: App\Entity\ProductTag
            label: 'Теги продуктов'
            controller: App\Controller\Admin\ProductTagController
            list:
              title: 'Теги продуктов'
              fields: ['id', 'name', 'created', 'visible', 'input_type']
            form:
              fields:
                - name
                - { property: 'type', type: 'choice', type_options: {multiple: false, choices: {bool: 'bool', string: 'string', int: 'int', float: 'float', enum: 'enum'}} }
                - { property: 'input_type', type: 'choice', type_options: {multiple: false, choices: {multiple: 'multiple', once: 'once'}} }
                - { property: 'visible', type: 'choice', type_options: {multiple: false, choices: {No: 'No', Yes: 'Yes'}}}
                - { property: 'productTagItems', type_options: { block_name: 'products_tags_items' }}
        ProductTagItem:
            class: App\Entity\ProductTagItem
            form:
              fields:
                - name
                - slug
        ProductItemTag:
            label: 'Теги товаров'
            class: App\Entity\ProductItemTag
            controller: App\Controller\Admin\ProductItemTagController
            list:
              title: 'Теги товаров'
              fields: ['id', 'name', 'visible', 'created']
            form:
              title: 'Тег товара'
              fields:
                - { property: 'name', label: 'Имя'}
                - { property: 'visible', label: 'Видимость' }
                - { property: 'productItemTagItems', label: 'Опции', type_options: { block_name: 'product_item_tag_items' }}
        ProductItemTagItem:
            class: App\Entity\ProductItemTagItem
            controller: App\Controller\Admin\ProductItemTagItemController
            list:
              title: 'Опции тегов товаров'
              fields:
                - id
                - name
                - { property: 'image', template: 'admin/renderers/image.html.twig' }
                - created
            form:
              title: 'Добавить опцию тега товара'
              fields:
                - { property: 'name', label: 'Имя'}
                - { property: 'entity', type_options: { block_name: 'entity_id'} }
                - { property: 'image', label: 'Изображение', type_options: { block_name: 'product_item_tag_image' }}
        CatalogTag:
            class: App\Entity\CatalogTag
            label: 'Теги каталогов'
            controller: App\Controller\Admin\ProductTagController
            list:
                title: 'Теги каталогов'
                fields: ['id', 'name', 'created', 'visible']
            form:
              fields:
                - name
                - { property: 'type', type: 'choice', type_options: {multiple: false, choices: {bool: 'bool', string: 'string', int: 'int', float: 'float', enum: 'enum'}} }
                - { property: 'visible', type: 'choice', type_options: {multiple: false, choices: {No: 'No', Yes: 'Yes'}}}

        Configuration:
            label: 'Конфигурация'
            class: App\Entity\ProductTag
            controller: App\Controller\Admin\ConfigurationController
        Address:
            class: App\Entity\Address
            list:
                fields: ['id', 'city', 'street']
            form:
                fields:
                    - person
                    - user_id
                    - zip
                    - region_id
                    - city
                    - street
                    - house
                    - corp
                    - level
                    - flat
                    - code
                    - comment
                    - active
        Banner:
            class: App\Entity\Banner
            label: 'Баннеры'
            list:
                title: 'Баннеры'
                fields:
                    - id
                    - path
                    - link
            form:
                fields:
                    - { property: 'pathFile', type: 'App\Form\Type\MultipleImage', type_options: { multiple: true, block_name: 'custom_title' } }
                    - link
        Sale:
            class: App\Entity\Sale
            label: 'Акции'
            form:
                fields:
                    - { type: 'tab' , label: 'General' }
                    - start
                    - finish
                    - category
                    - discount
                    - enabled
                    - featured
                    - type
                    - prior
                    - { property: 'imagePath', type: 'App\Form\Type\MultipleImage', type_options: { multiple: true, block_name: 'custom_image' } }
                    - { type: 'tab' , label: 'Products' }
                    - products
        City:
            class: App\Entity\City
            form:
                fields:
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType }
                    - { property: 'longitude'}
                    - { property: 'short_title'}
                    - { property: 'region'}
        Page:
            class: App\Entity\Page
            label: 'Страницы'
            controller: App\Controller\Admin\PageController
            list:
                title: 'Страницы'
                fields: ['id', 'title', 'name', 'visible']
            form:
                fields:
                    - { type: 'tab' , label: 'General' }
                    - title
                    - name
                    - visible
                    - { property: 'content', type: 'fos_ckeditor' }
                    - meta_keywords
                    - meta_description
                    - { type: 'tab', label: 'Page Urls' }
                    - { property: 'pageUrls', type_options: { block_name: 'page_urls' }}

        Direction:
            class: App\Entity\Direction
        District:
            class: App\Entity\District
        Pickup:
            class: App\Entity\Pickup
        Region:
            class: App\Entity\Region
        Courier:
            class: App\Entity\Courier
        UserAddress:
            class: App\Entity\UserAddress
    design:
        brand_color: 'black'
        form_theme:
            - 'admin/form/bootstrap_3_layout.html.twig'
            - 'admin/form/bootstrap_3_horizontal_layout.html.twig'
            - 'admin/form/images.html.twig'
            - 'admin/form/tags.html.twig'
            - 'admin/form/entity_id.html.twig'
            - 'admin/form/products_items.html.twig'
            - 'admin/form/products_catalogs.html.twig'
            - 'admin/form/products_tags_items.html.twig'
            - 'admin/form/catalogs_tags.html.twig'
            - 'admin/form/products_urls.html.twig'
            - 'admin/form/catalog_urls.html.twig'
            - 'admin/form/item_images.html.twig'
            - 'admin/form/page_urls.html.twig'
            - 'admin/form/product_item_tag_items.html.twig'
            - 'admin/form/product_item_tag_image.html.twig'
        menu:
          - label: 'Адреса'
            children: ['ProductUrl', 'CatalogUrl']
          - label: 'Каталоги'
            children: ['Catalog', 'Product', 'Items', 'ProductTag','ProductItemTag']
          - Users
          - label: 'Меню'
            children: ['Menu', 'MenuItem']
          - Page
          - Banner
          - Sale
          - Configuration
        assets:
            css:
                - '/bundles/lp/css/lp.css'
            js:
                - 'http://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.js'
                - '/bundles/lp/js/jq-ui.js'
                - '/bundles/lp/js/fileupload.js'