doctrine:
  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        mappings:
          Instashop:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/src/Bundles/InstashopBundle/Entity'
            prefix: 'App\Bundles\InstashopBundle\Entity'
            alias: Instashop

instashop:
  instagram:
    client_id: none
    token: none

easy_admin:
  entities:
    InstashopRaw:
      class: App\Bundles\InstashopBundle\Entity\Instashop
      label: 'Необработанные'
      controller: App\Bundles\InstashopBundle\Controller\InstashopController
      list:
        title: 'Необработанные изображения'
        actions:
          - { name: 'approve', label: 'Утвердить', css_class: 'text-success' }
          - { name: 'reject', label: 'Отклонить', css_class: 'text-danger' }
          - { name: '-edit' }
          - { name: '-delete' }
        fields:
          - { property: 'hash_tag', label: 'Хэш-тег' }
          - { property: 'path', type: 'image', label: 'Изображение' }
          - { property: 'created', format: 'j F Y', label: 'Дата импорта' }
        dql_filter: "entity.status = 'raw'"
      templates:
        list: 'admin/instashop/new.html.twig'
    InstashopApproved:
      class: App\Bundles\InstashopBundle\Entity\Instashop
      label: 'Утвержденные'
      controller: App\Bundles\InstashopBundle\Controller\InstashopController
      list:
        title: 'Утвержденные изображения'
        actions:
          - { name: '-delete' }
        fields:
          - { property: 'hash_tag', label: 'Хэш-тег' }
          - { property: 'path', type: 'image', label: 'Изображение' }
          - { property: 'created', format: 'j F Y', label: 'Дата импорта' }
          - { property: 'visible', type: 'boolean', label: 'Видимость' }
        dql_filter: "entity.status = 'approved'"
      edit:
        title: 'Редактирование утвержденного изображения'
        actions:
          - { name: '-delete' }
      form:
        fields:
          - { type: 'tab' , label: 'Продукты' }
          - {
              label: 'Закрепленные продукты',
              property: 'instashopProducts',
              type_options: {
                block_name: 'instashop_products',
              }
            }
          - { type: 'tab' , label: 'Мультиязычный контент' }
          - {
              property: 'translations',
              label: false,
              type: A2lix\TranslationFormBundle\Form\Type\TranslationsType ,
              type_options: {
                default_locale: '%locale%',
                fields: {
                  title: {field_type: 'Symfony\Component\Form\Extension\Core\Type\TextType' }
                    description: {field_type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
                }
              }
            }
          - { type: 'tab' , label: 'Дополнительно' }
          - { property: 'visible', label: 'Видимость'}
      templates:
        list: 'admin/instashop/approved.html.twig'
    InstashopRejected:
      class: App\Bundles\InstashopBundle\Entity\Instashop
      label: 'Отклоненные'
      controller: App\Bundles\InstashopBundle\Controller\InstashopController
      list:
        title: 'Отклоненные изображения'
        actions:
          - { name: 'approve', label: 'Утвердить', css_class: 'text-success' }
          - { name: '-edit' }
          - { name: '-delete' }
        fields:
          - { property: 'hash_tag', label: 'Хэш-тег' }
          - { property: 'path', type: 'image', label: 'Изображение' }
          - { property: 'created', format: 'j F Y', label: 'Дата импорта' }
        dql_filter: "entity.status = 'rejected'"
      templates:
        list: 'admin/instashop/rejected.html.twig'
  design:
    assets:
      favicon:
        path: '/admin/favicon.ico'
        mime_type: 'image/ico'
    brand_color: '#1ABC9C'
    menu:
      - label: 'Instashop'
        children: ['InstashopRaw', 'InstashopApproved', 'InstashopRejected']
