version: '2'
volumes:
    br-sync:
        external: true
services:
    br_php:
        container_name: br_php
        build: php-fpm
        ports:
            - '9008:9000'
        volumes:
            - br-sync:/var/www/symfony
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        links:
            - br_db
            - br_redis
        environment:
            REDIS_HOST: br_redis
            REDIS_PORT: 6379
        networks:
            main:
                aliases:
                    - br_php
    br_postgres:
        container_name: br_postgres
        image: postgres
        environment:
        - POSTGRES_DB=symfony
        - POSTGRES_USER=symfony
        - POSTGRES_PASSWORD=symfony
        - PGDATA=/var/lib/postgresql/data/db-files/
        ports:
        - "5432:5432"
        networks:
            main:
                aliases:
                    - br_postgres
    br_nginx:
        container_name: br_nginx
        build: nginx
        ports:
            - '8084:80'
            - '1343:1341'
        volumes_from:
            - br_php
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/:/var/log/nginx:cached
        networks:
            main:
                aliases:
                    - br_nginx
    br_db:
        container_name: br_db
        image: mariadb:latest
        restart: on-failure
        ports:
          - "3313:3306"
        volumes:
          - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
          - ./db:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=br
          - MYSQL_USER=root
        networks:
            main:
                aliases:
                    - mysql
    br_redis:
        container_name: br_redis
        image: redis:4-alpine
        networks:
            main:
                aliases:
                    - br_redis
networks:
    main:
