Banners:
  type: object
  config:
    description: "Banners"
    fields:
      data:
        type: "[Banner]"
Banner:
  type: object
  config:
    description: "Banner"
    fields:
      id:
        type: "Int!"
        description: "Banner Id"
      name:
        type: "String"
        description: "Name"
      bannerItems:
        type: "[BannerItem]"
BannerItem:
  type: object
  config:
    description: "Banner Item"
    fields:
      id:
        type: "Int!"
        description: "Banner Id."
      link:
        type: "String"
        description: "Link"
      path:
        type: "String"
        description: "Path"
      images:
        type: "ItemsImages"
        description: "Images"

