Basket:
  type: object
  config:
    description: "Basket"
    fields:
      products:
        type: "[BasketProduct]"
        description: "Basket Id."
BasketProduct:
  type: object
  config:
    description: "Basket Product"
    fields:
      item:
        type: "ProductItem"
        description: "Original Product Item"
      qty:
        type: "Int"
        description: "Qty"
      price:
        type: "String"
        description: "Price"