Catalog:
  type: object
  config:
    description: "Catalog"
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\CatalogFieldResolver", [info, value, args])'
    fields:
      id:
        type: "Int!"
        description: "Catalog Id."
      name:
        type: "String"
        description: "Catalog Name"
      banner:
        type: "String"
        description: "Catalog Banner"
      description:
        type: "String"
        description: "Catalog description"
      products:
        type: ProductConnection
        argsBuilder: PaginatoringBuilder
        resolve: '@=resolver("CatalogProduct", [value, args])'
      count:
        type: "Int!"
        description: "Count of products"
      tags:
        type: "[CatalogFilters]"
        description: "Catalog Filter"
      catalogUrls:
        type: "[CatalogUrl]"
        description: "Catalog Urls"

CatalogFilters:
  type: object
  config:
    description: "Catalog Filter Item"
    fields:
      id:
        type: "Int!"
        description: "Catalog Id."
      name:
        type: "String"
        description: "Catalog Filter Item Name"
      childrens:
        type: "[CatalogFilterItem]"
        description: "Catalog Filter Items Childrens"

CatalogFilterItem:
  type: object
  config:
    description: "Catalog Filter Item"
    fields:
      id:
        type: "Int!"
        description: "Catalog Filter Item Id."
      name:
        type: "String"
        description: "Catalog Filter Item Name"
      count:
        type: "Int"
        description: "Count products in selected filter"

CatalogUrl:
  type: object
  config:
    description: "Catalog Url Item"
    fields:
      id:
        type: "Int!"
        description: "Catalog Url Item Id."
      url:
        type: "String"
        description: "Catalog Url Item Name"