Instashop:
  type: object
  config:
    description: "Instashop"
    fields:
      data:
        type: InstashopConnection
        argsBuilder: PaginatoringBuilder
        resolve: '@=resolver("InstashopItem", [value, args])'

InstashopItem:
  type: object
  config:
    description: "Instashop Item"
    fields:
      id:
        type: "Int!"
        description: "ID"
      path:
        type: "String"
        description: "Path"
      tag:
        type: "String"
        description: "Path"
      title:
        type: "String"
        description: "Path"
      description:
        type: "String"
        description: "Path"
      purchases:
        type: "String"
        description: "Path"
      clicks:
        type: "String"
        description: "Path"
      products:
        type: "[InstashopProduct]"
        description: "Instashop Product"
InstashopProduct:
  type: object
  config:
    description: "Instashop Product"
    fields:
      id:
        type: "Int!"
        description: "Instashop Product Int"
