Order:
  type: object
  config:
    description: "Order"
    fields:
      id:
        type: "Int"
        description: "Order Id."
      secret_key:
        type: "String"
        description: "Secret Key"
      orderItems:
        type: "[OrderItem]"
        description: "Orders Items"
      payment:
        type: "ExternalPayment"
        description: "External Payment Item"
      delivery:
        type: "ExternalDelivery"
        description: "External Delivery Method"
      address_id:
        type: "Address"
        description: "Address Item"

ExternalPayment:
  type: object
  config:
    description: "External Payment"
    fields:
      id:
        type: "String"
        description: "External Payment Id"
      title:
        type: "String"
        description: "External Payment Title"
      description:
        type: "String"
        description: "External Payment Description"

ExternalDelivery:
  type: object
  config:
    description: "External Delivery"
    fields:
      id:
        type: "String"
        description: "External Delivery Id"
      comment:
        type: "String"
        description: "External Delivery Comment"
      service:
        type: "String"
        description: "External Delivery Service"
      address:
        type: "String"
        description: "External Delivery Address"
      schedule:
        type: "String"
        description: "External Delivery Schedule"
      latitude:
        type: "String"
        description: "External Delivery Latitude"
      longitude:
        type: "String"
        description: "External Delivery Longitude"
      days:
        type: "String"
        description: "External Delivery Days"
