OrderInput:
  type: input-object
  config:
    fields:
      external_delivery_code:
        type: "String"
        description: "External Delivery Code"
      external_payment_code:
        type: "String"
        description: "External Payment Code"
      comment:
        type: "String"
        description: "Comment"
      address_id:
        type: "Int"
        description: "User Address Id"
      lenses:
        type: "Int"
        description: "Lenses Configuration"