Order:
  type: object
  config:
    description: "Order"
    fields:
      id:
        type: "Int"
        description: "Order Id."
      secret_key:
        type: "String"
        description: "Secret Key"
      orderItems:
        type: "[OrderItem]"
        description: "Orders Items"