OrderInput:
  type: input-object
  config:
    fields:
      pickup_id:
        type: "Int"
        description: "Pvz ID"
      payment_method_code:
        type: "String"
        description: "Payment Method Code"
      comment:
        type: "String"
        description: "Comment"
      courier_id:
        type: "Int"
        description: "Courier ID"
      address_id:
        type: "Int"
        description: "User Address Id"
      lenses:
        type: "Int"
        description: "Lenses Configuration"