ProductItem:
  type: object
  config:
    description: "Product Item"
    fields:
      id:
        type: "Int!"
        description: "Product Item Id."
      name:
        type: "String"
        description: "Product Item Name"
      price:
        type: "String"
        description: "Product Item Price"
      productItemImages:
        type: "[ProductItemImage]"
        description: "Product Item Image"
      productItemTagItems:
        type: "[ProductItemTagItem]"
        description: "Product Item Tag Item"

ProductItemImage:
  type: object
  config:
    description: "Product Item Image"
    fields:
      id:
        type: "String"
        description: "Product Image Id"
      path:
        type: "String"
        description: "Product Image Path"

ProductItemTagItem:
  type: object
  config:
    description: "Product Item Tag Item"
    fields:
      id:
        type: "String"
        description: "Product Item Tag Item Id"
      name:
        type: "String"
        description: "Product Item Tag Item Path"
      image:
        type: "String"
        description: "Product Item Tag Item Image"