Product:
  type: object
  config:
    description: "Product"
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\ProductFieldResolver", [info, value, args])'
    fields:
      id:
        type: "Int!"
        description: "Product Id."
      name:
        type: "String"
        description: "Product Name"
      url:
        type: "String"
        description: "Product Url"
      items:
        type: ItemConnection
        argsBuilder: PaginatoringBuilder
      lenses:
        type: "[Lense]"
        description: "Lenses Configuration"
      catalog:
        type: "[Catalog]"
        description: "Product Catalog"
      tags:
        type: "[ProductFilters]"
        description: "Product Filter"
      similars:
        type: ProductConnection
        argsBuilder: PaginatoringBuilder
        resolve: '@=resolver("SimilarProduct", [value, args])'
ProductFilters:
  type: object
  config:
    description: "Product Filter Item"
    fields:
      name:
        type: "String"
        description: "Product Filter Name."
      value:
        type: "String"
        description: "Product Filter Value"
ProductCatalog:
  type: object
  config:
    description: "Product Catalog Item"
    fields:
      name:
        type: "String"
        description: "Product Catalog Name."
      value:
        type: "String"
        description: "Product Catalog Value"

Steps:
  type: object
  config:
    fields:
      steps:
        type: "[Step]"
        description: "Step Configuration"

Step:
  type: object
  config:
    description: "Lenses Items"
    fields:
      name:
        type: "String"
        description: "Lense Name"
      price:
        type: "String"
        description: "Lense Price"

Lense:
  type: object
  config:
    description: "Lense Item"
    fields:
      name:
        type: "String"
        description: "Lense Item Name"
      price:
        type: "String"
        description: "Lense Item Price"
      lenseitemstags:
        type: "[LenseItem]"
        description: Lenses Tags Items

LenseItem:
  type: object
  config:
    description: "Lenses Tags Items"
    fields:
      name:
        type: "String"
        description: "Name of Lense Item Tag"
      visible:
        type: "String"
        description: "Lense Name"
      price:
        type: "String"
        description: "Lense Price"
      entity:
        type: "LenseItemTag"
        description: "Lenses Configuation"

LenseItemTag:
  type: object
  config:
    description: "Lense Item"
    fields:
      name:
        type: "String"
        description: "Lense Item Name"
      price:
        type: "String"
        description: "Lense Item Price"
      visible:
        type: "Boolean"
        description: "Lense Item Visibility"
