ProductMini:
  type: object
  config:
    description: "Product Thumb"
    fields:
      id:
        type: "Int!"
        description: "Product Id."
      name:
        type: "String"
        description: "Product Name"
      items:
        type: ItemConnection
        argsBuilder: PaginatoringBuilder