Query:
  type: object
  config:
    description: "Product Item ORM repository"
    fields:
      productitem:
        type: "ProductItem"
        args:
            id:
              description: "Resolves using the product item id."
              type: "Int"
            locale:
              description: "Locale"
              type: "String"
        resolve: "@=resolver('ProductItem', [args])"
      user:
        type: "User"
        resolve: "@=resolver('User', [args])"
      product:
        type: "Product"
        args:
            id:
              description: "Resolves using the product ID."
              type: "Int"
            slug:
              description: "Resolves using the product slug."
              type: "String"
            locale:
              description: "Locale"
              type: "String"
        resolve: "@=resolver('Product', [args])"
      catalog:
        type: "Catalog"
        args:
            id:
              description: "Resolves using the catalog ID."
              type: "Int"
            slug:
              description: "Resolves using the catalog slug."
              type: "String"
            products:
              description: 'Products'
              type: "String"
            tags:
              description: 'Tags'
              type: "[Int]"
            locale:
              description: "Locale"
              type: "String"
        resolve: "@=resolver('Catalogs', [args])"
      page:
        type: "Page"
        args:
            id:
              description: "Resolves using the page ID."
              type: "Int"
            slug:
              description: "Resolves using the page slug."
              type: "String"
            locale:
              description: "Locale"
              type: "String"
        resolve: "@=resolver('Page', [args])"
      block:
        type: "Block"
        args:
            id:
              description: "Resolves using the block ID."
              type: "String"
            locale:
              description: "Locale"
              type: "String"
        resolve: "@=resolver('Block', [args])"
      addresses:
        type: "Addresses"
        args:
          token:
            description: "User Token"
            type: "String"
        resolve: "@=resolver('Addresses', [args])"
      basket:
        type: "Basket"
        resolve: "@=resolver('Basket', [args])"
        args:
          locale:
            description: "Locale"
            type: "String"
      users_orders:
        type: "UsersOrders"
        resolve: "@=resolver('UsersOrders', [args])"
      banner:
        type: "Banner"
        resolve: "@=resolver('Banner', [args])"
        args:
          locale:
            description: "Locale"
            type: "String"
          name:
            description: "Name"
            type: "String"
      sale:
        type: "Sale"
        args:
            limit:
              description: "Sale Limit"
              type: "Int"
        resolve: "@=resolver('Sales', [args])"
      regions:
        type: "Regions"
        resolve: "@=resolver('Regions', [args])"
        args:
          locale:
            description: "Locale"
            type: "String"
      cities:
        type: "Cities"
        resolve: "@=resolver('Cities', [args])"
      directions:
        type: "Directions"
        resolve: "@=resolver('Directions', [args])"
      districts:
        type: "Districts"
        resolve: "@=resolver('Districts', [args])"
      pickups:
        type: "Pickups"
        resolve: "@=resolver('Pickups', [args])"
        args:
            city_id:
              description: "City ID"
              type: "Int"
      couriers:
        type: "Couriers"
        resolve: "@=resolver('Couriers', [args])"
        args:
            city_id:
              description: "City ID"
              type: "Int"
      payments_methods:
        type: "PaymentsMethods"
        resolve: "@=resolver('PaymentsMethods', [args])"
      top_menu:
        type: "Menu"
        resolve: "@=resolver('TopMenu', [args])"
        args:
            locale:
              description: "Locale"
              type: "String"
      menu:
        type: "Menu"
        resolve: "@=resolver('Menu', [args])"
        args:
            name:
              description: "Name"
              type: "String"
            locale:
              description: "Locale"
              type: "String"
      brands_list:
        type: "CatalogThumb"
        resolve: "@=resolver('BrandsList', [args])"
      address:
        type: "Address"
        resolve: "@=resolver('Address', [args])"
        args:
            id:
              description: "Address ID"
              type: "Int"
      stores:
        type: "Stores"
        resolve: "@=resolver('Stores', [args])"
        args:
            check_vision:
              description: "Check vision option"
              type: "Int"
            locale:
              description: "Locale"
              type: "String"
      store:
        type: "Store"
        args:
            slug:
              description: "Resolves using the store slug."
              type: "String"
            locale:
              description: "Locale"
              type: "String"
        resolve: "@=resolver('Store', [args])"
      catalog_search:
        type: "CatalogSearch"
        args:
            name:
              description: "Search Name"
              type: "String"
        resolve: "@=resolver('CatalogSearch', [args])"
      order:
        type: "Order"
        args:
            secret_key:
              description: "Resolves using the order secret key."
              type: "String"
            locale:
              description: "Locale"
              type: "String"
        resolve: "@=resolver('Order', [args])"
      wholesale:
        type: "Wholesale"
        resolve: "@=resolver('Wholesale', [args])"
      instashop_images:
        type: "Instashop"
        args:
          tag:
            description: "By Tag"
            type: "String"
          item_id:
            description: "By Item ID"
            type: "Int"
          product_id:
            description: "By Product ID"
            type: "Int"
          locale:
            description: "Locale"
            type: "String"
        resolve: "@=resolver('Instashop', [args])"
DateTime:
    type: custom-scalar
    config:
        serialize: ["App\\GraphQL\\Type\\DateTimeType", "serialize"]
        parseValue: ["App\\GraphQL\\Type\\DateTimeType", "parseValue"]
        parseLiteral: ["App\\GraphQL\\Type\\DateTimeType", "parseLiteral"]