Recipe:
  type: object
  config:
    description: "Recipe Entity"
    fields:
      id:
        type: "Int!"
        description: "User Id."
      recipe:
        type: "LensesRecipe"
        description: "Recipe"
      customer:
        type: "User"
        description: "User"