Result:
  type: object
  config:
    description: "Result"
    fields:
      success:
        type: "Boolean"
        description: "Is successfull"
      message:
        type: "String"
        description: "Success Message"