Stores:
  type: object
  config:
    description: "Stores"
    fields:
      data:
       type: "[Store]"
Store:
  type: object
  config:
    description: "Store"
    fields:
      id:
        type: "Int"
        description: "Store ID"
      name:
        type: "String"
        description: "Store Name"
      full_name:
        type: "String"
        description: "Full Store Name"
      city:
        type: "String"
        description: "Store City"
      visible:
        type: "String"
        description: "Visibility"
      longitude:
        type: "String"
        description: "Longitude"
      latitude:
        type: "String"
        description: "Latitude"
      storeUrls:
        type: "[StoreUrl]"
        description: "Store Url"
      check_vision:
        type: "Boolean"
        description: "Check Vision param"
StoreUrl:
  type: object
  config:
    description: "Store Url"
    fields:
      id:
        type: "Int"
        description: "Store ID"
      url:
        type: "String"
        description: "Store Url"