UsersOrders:
  type: object
  config:
    description: "Users Orders"
    fields:
      orders:
       type: "[UserOrder]"
UserOrder:
  type: object
  config:
    description: "User Order"
    fields:
      id:
        type: "Int"
        description: "Order Id"
      orderItems:
        type: "[OrderItem]"
        description: "Order Item Id."
OrderItem:
  type: object
  config:
    description: "Order Item"
    fields:
      id:
        type: "Int"
        description: "Order Item Id"
      item:
        type: "ProductItem"
        description: "Basket Product Item"
      qty:
        type: "Int"
        description: "Qty"
      name:
        type: "String"
        description: "Product Name"
      price:
        type: "String"
        description: "Price"
      coupon_price:
        type: "String"
        description: "Coupon Price"
      lense:
        type: "LensesRecipe"
        description: "Price"
