User:
  type: object
  config:
    description: "User"
    fields:
      id:
        type: "Int!"
        description: "User Id."
      email:
        type: "String"
        description: "Email"
      gender:
        type: "String"
        description: "Gender"
      firstname:
        type: "String"
        description: "First Name"
      lastname:
        type: "String"
        description: "Last Name"
      phone:
        type: "String"
        description: "Phone"
      addresses:
        type: "[Address]"
        description: "Users Addresses"
      orders:
        type: "[Order]"
        description: "Users Orders"
      recipes:
        type: "[Recipe]"
        description: "Users Recipes"
      confirmationToken:
        type: "String"
        description: "Confirmation Token"