app_logout:
    path: /logout

images_upload:
    path: /admin/images/upload
    controller: App\Controller\Admin\ImagesController::upload

images_once_upload:
    path: /admin/images/upload_once
    controller: App\Controller\Admin\ImagesController::upload_once

images_delete:
    path: /admin/images/delete
    controller: App\Controller\Admin\ImagesController::delete

easy_admin_bundle:
    resource: 'App\Controller\AdminController'
    prefix: /admin
    type: annotation

app_yandex:
    resource: "Lp/PaymentBundle/Resources/config/routing.yaml"

bundles:
    resource: "@InstashopBundle/Resources/config/routing.yaml"