services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Bundles\InstashopBundle\:
      resource: '../../*'
      exclude: '../../{DependencyInjection,Entity,Migrations,Tests}'

  App\Bundles\InstashopBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']